// SPDX-License-Identifier: UNLICENSED
// Generated by Qoin Maker 0.1.0
// Generator license: QMSAL-1.0 (source-available). See the Qoin Maker repo.
// This generated contract is provided AS IS. Have it reviewed before mainnet.
// Not affiliated with Qoin (qoin.com) or Post-Quantum Qoin.
pragma solidity ^0.8.24;

contract GCIICoin {
    string public constant name = "GCII Coin";
    string public constant symbol = "GCII";
    uint8 public constant decimals = 11;

    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;
    address public owner;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    constructor() {
        owner = msg.sender;
        emit OwnershipTransferred(address(0), msg.sender);
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "not owner");
        _;
    }

    function transferOwnership(address next) external onlyOwner {
        require(next != address(0), "zero owner");
        emit OwnershipTransferred(owner, next);
        owner = next;
    }
    function transfer(address to, uint256 value) external returns (bool) {
        _transfer(msg.sender, to, value);
        return true;
    }

    function approve(address spender, uint256 value) external returns (bool) {
        allowance[msg.sender][spender] = value;
        emit Approval(msg.sender, spender, value);
        return true;
    }

    function transferFrom(address from, address to, uint256 value) external returns (bool) {
        uint256 allowed = allowance[from][msg.sender];
        if (allowed != type(uint256).max) {
            require(allowed >= value, "allowance");
            allowance[from][msg.sender] = allowed - value;
        }
        _transfer(from, to, value);
        return true;
    }

    function _transfer(address from, address to, uint256 value) internal {
        require(to != address(0), "zero to");
        uint256 bal = balanceOf[from];
        require(bal >= value, "balance");
        unchecked {
            balanceOf[from] = bal - value;
            balanceOf[to] += value;
        }
        emit Transfer(from, to, value);
    }

    function _mint(address to, uint256 value) internal {
        require(to != address(0), "zero to");
        totalSupply += value;
        balanceOf[to] += value;
        emit Transfer(address(0), to, value);
    }

    function _burn(address from, uint256 value) internal {
        uint256 bal = balanceOf[from];
        require(bal >= value, "balance");
        unchecked {
            balanceOf[from] = bal - value;
            totalSupply -= value;
        }
        emit Transfer(from, address(0), value);
    }
    function mint(address to, uint256 wholeTokens) external onlyOwner {
        require(to != address(0), "zero to");
        uint256 raw = wholeTokens * (10 ** uint256(decimals));
        _mint(to, raw);
    }
    function burn(uint256 wholeTokens) external {
        uint256 raw = wholeTokens * (10 ** uint256(decimals));
        _burn(msg.sender, raw);
    }

    function burnFrom(address from, uint256 wholeTokens) external {
        uint256 raw = wholeTokens * (10 ** uint256(decimals));
        uint256 allowed = allowance[from][msg.sender];
        require(allowed >= raw, "allowance");
        if (allowed != type(uint256).max) {
            allowance[from][msg.sender] = allowed - raw;
        }
        _burn(from, raw);
    }
}
