"""Solidity and project file templates.

Templates emit standard, inspectable ERC-20 contracts. Hidden-tax,
honeypot, and blacklist-drain patterns are intentionally absent.
"""

from __future__ import annotations

from textwrap import dedent

from .validate import solidity_identifier


HEADER = dedent(
    """\
    // SPDX-License-Identifier: UNLICENSED
    // Generated by Qoin Maker {version}
    // Generator license: QMSAL-1.0 (source-available). See the Qoin Maker repo.
    // This generated contract is provided AS IS. Have it reviewed before mainnet.
    // Not affiliated with Qoin (qoin.com) or Post-Quantum Qoin.
    pragma solidity ^0.8.24;
    """
)


def _escape(value: str) -> str:
    return value.replace("\\", "").replace('"', "")


def _indent(block: str, spaces: int = 4) -> str:
    pad = " " * spaces
    lines = block.strip("\n").split("\n")
    return "\n".join(pad + line if line.strip() else "" for line in lines) + "\n"


def erc20_contract(
    *,
    name: str,
    symbol: str,
    decimals: int,
    initial_supply: int,
    mintable: bool,
    burnable: bool,
    capped: bool,
    cap: int | None,
    ownable: bool,
    version: str,
) -> str:
    ident = solidity_identifier(name.replace(" ", ""), "GeneratedToken")
    if capped and cap is None:
        cap = initial_supply
    cap = cap or initial_supply

    ownable_state = ""
    ownable_mod = ""
    ownable_ctor = ""
    if ownable or mintable:
        ownable_state = "    address public owner;\n"
        ownable_mod = _indent(
            dedent(
                """\
                modifier onlyOwner() {
                    require(msg.sender == owner, "not owner");
                    _;
                }

                function transferOwnership(address next) external onlyOwner {
                    require(next != address(0), "zero owner");
                    emit OwnershipTransferred(owner, next);
                    owner = next;
                }
                """
            )
        )
        ownable_ctor = "        owner = msg.sender;\n        emit OwnershipTransferred(address(0), msg.sender);\n"

    mint_fn = ""
    if mintable:
        cap_line = '        require(totalSupply + raw <= cap, "cap exceeded");\n' if capped else ""
        mint_fn = (
            "    function mint(address to, uint256 wholeTokens) external onlyOwner {\n"
            '        require(to != address(0), "zero to");\n'
            "        uint256 raw = wholeTokens * (10 ** uint256(decimals));\n"
            + cap_line
            + "        _mint(to, raw);\n"
            + "    }\n"
        )

    burn_fn = ""
    if burnable:
        burn_fn = _indent(
            dedent(
                """\
                function burn(uint256 wholeTokens) external {
                    uint256 raw = wholeTokens * (10 ** uint256(decimals));
                    _burn(msg.sender, raw);
                }

                function burnFrom(address from, uint256 wholeTokens) external {
                    uint256 raw = wholeTokens * (10 ** uint256(decimals));
                    uint256 allowed = allowance[from][msg.sender];
                    require(allowed >= raw, "allowance");
                    if (allowed != type(uint256).max) {
                        allowance[from][msg.sender] = allowed - raw;
                    }
                    _burn(from, raw);
                }
                """
            )
        )

    cap_state = "    uint256 public immutable cap;\n" if capped else ""
    cap_ctor = (
        f"        cap = {cap} * (10 ** uint256(decimals));\n"
        f"        require({initial_supply} * (10 ** uint256(decimals)) <= cap, \"supply > cap\");\n"
        if capped
        else ""
    )

    events = [
        "    event Transfer(address indexed from, address indexed to, uint256 value);",
        "    event Approval(address indexed owner, address indexed spender, uint256 value);",
    ]
    if ownable or mintable:
        events.append(
            "    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);"
        )

    body = _indent(
        dedent(
            """\
            function transfer(address to, uint256 value) external returns (bool) {
                _transfer(msg.sender, to, value);
                return true;
            }

            function approve(address spender, uint256 value) external returns (bool) {
                allowance[msg.sender][spender] = value;
                emit Approval(msg.sender, spender, value);
                return true;
            }

            function transferFrom(address from, address to, uint256 value) external returns (bool) {
                uint256 allowed = allowance[from][msg.sender];
                if (allowed != type(uint256).max) {
                    require(allowed >= value, "allowance");
                    allowance[from][msg.sender] = allowed - value;
                }
                _transfer(from, to, value);
                return true;
            }

            function _transfer(address from, address to, uint256 value) internal {
                require(to != address(0), "zero to");
                uint256 bal = balanceOf[from];
                require(bal >= value, "balance");
                unchecked {
                    balanceOf[from] = bal - value;
                    balanceOf[to] += value;
                }
                emit Transfer(from, to, value);
            }

            function _mint(address to, uint256 value) internal {
                require(to != address(0), "zero to");
                totalSupply += value;
                balanceOf[to] += value;
                emit Transfer(address(0), to, value);
            }

            function _burn(address from, uint256 value) internal {
                uint256 bal = balanceOf[from];
                require(bal >= value, "balance");
                unchecked {
                    balanceOf[from] = bal - value;
                    totalSupply -= value;
                }
                emit Transfer(from, address(0), value);
            }
            """
        )
    )

    return (
        HEADER.format(version=version)
        + "\n"
        + f"contract {ident} {{\n"
        + f'    string public constant name = "{_escape(name)}";\n'
        + f'    string public constant symbol = "{_escape(symbol)}";\n'
        + f"    uint8 public constant decimals = {decimals};\n\n"
        + "    uint256 public totalSupply;\n"
        + "    mapping(address => uint256) public balanceOf;\n"
        + "    mapping(address => mapping(address => uint256)) public allowance;\n"
        + cap_state
        + ownable_state
        + "\n"
        + "\n".join(events)
        + "\n\n"
        + "    constructor() {\n"
        + ownable_ctor
        + cap_ctor
        + (
            f"        _mint(msg.sender, {initial_supply} * (10 ** uint256(decimals)));\n"
            if initial_supply > 0
            else ""
        )
        + "    }\n\n"
        + ownable_mod
        + body
        + mint_fn
        + burn_fn
        + "}\n"
    )


def foundry_toml() -> str:
    return dedent(
        """\
        [profile.default]
        src = "src"
        out = "out"
        libs = ["lib"]
        solc = "0.8.24"
        optimizer = true
        optimizer_runs = 200
        evm_version = "cancun"

        [rpc_endpoints]
        base = "${BASE_RPC_URL}"
        sepolia = "${SEPOLIA_RPC_URL}"
        """
    )


def deploy_script(ident: str) -> str:
    return dedent(
        f"""\
        // SPDX-License-Identifier: UNLICENSED
        pragma solidity ^0.8.24;

        import "forge-std/Script.sol";
        import "../src/{ident}.sol";

        contract Deploy is Script {{
            function run() external {{
                uint256 pk = vm.envUint("PRIVATE_KEY");
                vm.startBroadcast(pk);
                {ident} token = new {ident}();
                vm.stopBroadcast();
                console2.log("token", address(token));
            }}
        }}
        """
    )


def token_readme(
    *,
    name: str,
    symbol: str,
    decimals: int,
    initial_supply: int,
    features: list[str],
    chain: str,
) -> str:
    feat = ", ".join(features) if features else "standard ERC-20"
    return dedent(
        f"""\
        # {name} (`{symbol}`)

        Generated by **Qoin Maker**. Review, test, and audit before mainnet.

        | Field | Value |
        |---|---|
        | Name | {name} |
        | Symbol | {symbol} |
        | Decimals | {decimals} |
        | Initial supply (whole tokens) | {initial_supply} |
        | Features | {feat} |
        | Target chain hint | {chain} |

        ## Safety

        - This is a plain ERC-20. There is no hidden fee, blacklist drain, or
          upgrade proxy in the default template.
        - `msg.sender` of the deploy transaction receives the initial supply.
        - If mintable, the deployer is `owner` and can mint until any cap.
        - Transfer ownership or lock the deployer key before you market the token.
        - Deployment costs gas on the target chain.

        ## Foundry

        ```bash
        forge build
        forge script script/Deploy.s.sol --rpc-url $BASE_RPC_URL --broadcast
        ```

        ## License of this generated project

        UNLICENSED / All rights reserved by the deployer unless you add a license.
        Qoin Maker's generator license does not make your token open source.
        """
    )
